name: Test with Pytest using Conda

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: mamba-org/setup-micromamba@v2
        with:
          python-version: 3.13.3
          environment-file: environment.yml
          activate-environment: stitching
      - name: Run Pytest
        shell: micromamba-shell -l {0}  # ensures conda env is loaded
        run: pytest .tests  # adjust if your tests are elsewhere
