name: Test with Pytest using Conda

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: mamba-org/setup-micromamba@v2
        with:
          python-version: 3.13.3
          environment-file: environment.yaml
          init-shell: >-
            bash
            powershell
          cache-environment: true
          post-cleanup: 'all'
          
      - name: Import numpy in micromamba environment (bash)
        run: python -c "import numpy"
        shell: bash -el {0}
      - name: Import numpy in micromamba environment (pwsh)
        run: python -c "import numpy"
        shell: pwsh
      - name: Run custom command in micromamba environment
        run: pytest .tests
        shell: micromamba-shell {0}
        
