name: Test with Pytest using Conda

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Install conda
        uses: conda-incubator/setup-miniconda@v2.0.1 # https://github.com/conda-incubator/setup-miniconda.
        with:
          channels: conda-forge,bioconda,defaults
          channel-priority: true
          environment-file: environment.yaml
          activate-environment: stitching
          auto-activate-base: true
      - name: Test
        shell: bash -l {0}  # Needed for conda
        run: pytest .tests
        
